# Sample .travis.yml for R projects from https://github.com/craigcitro/r-travis
# https://github.com/craigcitro/r-travis/wiki

language: c

env:
   global:
     - WARNINGS_ARE_ERRORS=1
     - R_BUILD_ARGS=" "
     - R_CHECK_ARGS="--as-cran"
     - BOOTSTRAP_LATEX="1"
   matrix:
     - NOT_CRAN="true"
     - NOT_CRAN="false"

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap

install:
  - ./travis-tool.sh install_deps
  - ./travis-tool.sh github_package jimhester/covr

script: ./travis-tool.sh run_tests

on_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - Rscript -e 'library(covr);coveralls()'